### ISSUE TITLE
Guardrail #5

### ISSUE THREAD

**Issue by XangoXCC** [canada-ca/cloud-guardrails#13]
Given that the Data residency policy has been updated April 1st to no longer require Canadian data residency is there a plan to remove Guardrail 5?

Refer to https://www.tbs-sct.gc.ca/pol/doc-eng.aspx?id=32601 section 4.4.1.10

**Comment by ptd-tbs** [comment]
No, there is no plan to change the guardrail. Data should stay in Canada unless a department obtains approval via GC EARB to proceed otherwise. TBS/SSC will continue to monitor this guardrail.
