### ISSUE TITLE
Bug - Missing page since V2 update: Cloud Usage Profiles Applicable Scope

### ISSUE THREAD

**Issue by ssc-cto-science** [canada-ca/cloud-guardrails#149]
When the new V2 Guardrails were merged into this repository (as part of commit 6a0ab3f), file _**00_Applicable-Scope.md**_ was deleted.

This file was useful and important since it had two tables, **Cloud Usage Profiles** and **Applicability of Guardrails to Cloud Usage Profiles**, whose information isn't defined anywhere else.  These tables are referenced regularly when dealing with both clients and their workloads as well as various service lines and security teams.

Please return the page in the repo.

**Comment by lcampbell2** [comment]
Thank you for pointing this out. The tables can be found on this new [canada.ca page](https://www.tbs-sct.canada.ca/pol/doc-eng.aspx?id=32787), which is the authoritative source for the cloud guardrails going forward. We will update the repo to include the new Cloud Usage Profile in the near future.
