### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by AndrewSouter** [canada-ca/cloud-guardrails#21]
Links to SPIN 2017-01 and ITPIN 2017-02 are broken in many sections.

**Comment by KenMorencyTC** [comment]
I've created a PR to fix the 2 links in the top level readme.
I'll try to find some time to help out and update others ASAP.

**Comment by gc-ianbell** [comment]
I put out a [message on GCCollab](https://gccollab.ca/discussion/view/5575720/enlooking-for-link-to-spin-2017-01fr) a few weeks ago and got a private response. I suggested that as redirect be put in on the original URLs. I'm not sure if that will happen. 

I keep finding broken links, today I find on [this page](https://github.com/canada-ca/cloud-guardrails/blob/master/EN/07_Protect-Data-in-Transit.md) a link to it's Considerations for Cryptography in Commercial Cloud Services, which should go to [this page here](https://www.canada.ca/en/government/system/digital-government/digital-government-innovations/cloud-services/government-canada-consideration-use-cryptography-in-cloud.html)

I really appreciate the links to the relevant docs - it makes my life a lot easier, so I'll do additional pull requests as I find them in the future.

**Comment by ptd-tbs** [comment]
Resolved with PR #22 and #23 .
