### ISSUE TITLE
ITSG-22 link broken on 08_Segmentation.md

### ISSUE THREAD

**Issue by ipnextgen** [canada-ca/cloud-guardrails#54]
Hi,

The link to ITSG-22 is broken on this page.

https://github.com/canada-ca/cloud-guardrails/blob/master/EN/08_Segmentation.md

You could maybe have a broken link checking job in some pipeline to be notified if there's any

Thanks

Martin

**Comment by nschonni** [comment]
There is a pipeline https://github.com/canada-ca/cloud-guardrails/blob/master/.github/workflows/link-check.yml but I'm not sure why it's not failing for this one

**Comment by ptd-tbs** [comment]
Updated link - https://www.cyber.gc.ca/en/guidance/baseline-security-requirements-network-security-zones-version-20-itsp80022
